--- #YAML:1.0
name:                Tie-CheckVariables
version:             0.03
abstract:            check/validate variables for their datatype
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Renee Baecker <module@renee-baecker.de>
